# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_function <- function(data) {
    .Call(`_fastorplayground_cpp_function`, data)
}

